In [1]:
import pandas as pd
import math

In [8]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     -------------------------------------- 250.0/250.0 kB 5.1 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: C:\Users\Jalal\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [12]:
# Charger le fichier pour avoir un aperçu des premières lignes
df_bikeshops = pd.read_excel("C:/Users/Jalal/Desktop/Projet_MrSelami/data/bikeshops.xlsx")
df_bikeshops.head()

,bikeshop.id,bikeshop.name,bikeshop.city,bikeshop.state,latitude,longitude
0,1,Pittsburgh Mountain Machines,Pittsburgh,PA,40.440625,-79.995886
1,2,Ithaca Mountain Climbers,Ithaca,NY,42.443961,-76.501881
2,3,Columbus Race Equipment,Columbus,OH,39.961176,-82.998794
3,4,Detroit Cycles,Detroit,MI,42.331427,-83.045754
4,5,Cincinnati Speed,Cincinnati,OH,39.103118,-84.512020

In [16]:
# Afficher les premières lignes pour vérifier l'importation
print(df_bikeshops.head())

# Statistiques descriptives pour une colonne numérique pertinente
# Remplacer 'nom_colonne_numerique' par le nom de la colonne numérique pour laquelle vous voulez des statistiques
print(df_bikeshops['bikeshop.id'].describe())

# Calcul de l'écart type pour la même colonne
print(df_bikeshops['bikeshop.id'].std())

# Compter le nombre d'occurrences pour une colonne catégorielle
# Remplacer 'nom_colonne_categorique' par le nom de la colonne catégorielle
print(df_bikeshops['bikeshop.city'].value_counts())

# Prix (ou autre mesure) moyen par catégorie
# Remplacer 'nom_colonne_categorique' et 'nom_colonne_numerique' par les noms réels
print(df_bikeshops.groupby('bikeshop.city')['bikeshop.id'].mean())

   bikeshop.id                 bikeshop.name bikeshop.city bikeshop.state  \
0            1  Pittsburgh Mountain Machines    Pittsburgh             PA
1            2      Ithaca Mountain Climbers        Ithaca             NY
2            3       Columbus Race Equipment      Columbus             OH
3            4                Detroit Cycles       Detroit             MI
4            5              Cincinnati Speed    Cincinnati             OH

    latitude  longitude
0  40.440625 -79.995886
1  42.443961 -76.501881
2  39.961176 -82.998794
3  42.331427 -83.045754
4  39.103118 -84.512020
count    30.000000
mean     15.500000
std       8.803408
min       1.000000
25%       8.250000
50%      15.500000
75%      22.750000
max      30.000000
Name: bikeshop.id, dtype: float64
8.803408430829505
bikeshop.city
Pittsburgh       1
Ithaca           1
Indianapolis     1
Wichita          1
San Antonio      1
Miami            1
New Orleans      1
Providence       1
Philadelphia     1
Ann Arbor        1
Seattle          1
Portland         1
San Francisco    1
Los Angeles      1
Las Vegas        1
Phoenix          1
Austin           1
Albuquerque      1
Oklahoma City    1
Dallas           1
New York         1
Kansas City      1
Minneapolis      1
Denver           1
Nashville        1
Louisville       1
Cincinnati       1
Detroit          1
Columbus         1
Tampa            1
Name: count, dtype: int64
bikeshop.city
Albuquerque      14.0
Ann Arbor        22.0
Austin           15.0
Cincinnati        5.0
Columbus          3.0
Dallas           12.0
Denver            8.0
Detroit           4.0
Indianapolis     29.0
Ithaca            2.0
Kansas City      10.0
Las Vegas        17.0
Los Angeles      18.0
Louisville        6.0
Miami            26.0
Minneapolis       9.0
Nashville         7.0
New Orleans      25.0
New York         11.0
Oklahoma City    13.0
Philadelphia     23.0
Phoenix          16.0
Pittsburgh        1.0
Portland         20.0
Providence       24.0
San Antonio      27.0
San Francisco    19.0
Seattle          21.0
Tampa            30.0
Wichita          28.0
Name: bikeshop.id, dtype: float64